services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - 8088:8000
    depends_on:
      - db
      - redis
      # - celery_worker
    env_file:
      - .env
    networks:
      - crypto_network

  db:
    image: postgres:17.1
    env_file:
      - .env
    ports:
      - "5438:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - crypto_network
  
  # celery_worker:
  #   build:
  #     context: .
  #   command: celery -A src.tasks.celery_app worker --loglevel=info --concurrency=2
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - redis
  #   env_file:
  #     - .env
  #   environment:
  #     CELERY_BROKER_URL: redis://redis:6379/0
  #   networks:
  #     - crypto_network

  redis:
    image: redis:8.0
    ports:
      - "6388:6379"
    networks:
      - crypto_network 

volumes:
  pgdata:

networks:
  crypto_network:
    driver: bridge 