services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - 8088:8000
    depends_on:
      - db
      - redis
    env_file:
      - .env
    networks:
      - bullbot_network
    deploy:
      resources:
        limits:
          memory: 400M
        reservations:
          memory: 200M

  db:
    image: postgres:17.1-alpine
    env_file:
      - .env
    ports:
      - "5438:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - bullbot_network
    deploy:
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 100M
    command: >
      postgres
      -c max_connections=20
      -c shared_buffers=32MB
      -c effective_cache_size=128MB
      -c maintenance_work_mem=16MB
  
  celery_worker:
    build:
      context: .
    command: celery -A src.tasks.celery_app worker --loglevel=info --concurrency=1 --max-memory-per-child=200000
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    env_file:
      - .env
    networks:
      - bullbot_network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
      
  celery_beat:
    build:
      context: .
    command: celery -A src.tasks.celery_app beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    env_file:
      - .env
    networks:
      - bullbot_network
    deploy:
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 100M

  redis:
    image: redis:8.0-alpine
    ports:
      - "6379:6379"
    networks:
      - bullbot_network
    deploy:
      resources:
        limits:
          memory: 100M
        reservations:
          memory: 50M
    command: >
      redis-server
      --maxmemory 64mb
      --maxmemory-policy allkeys-lru
      --save "" 

volumes:
  pgdata:

networks:
  bullbot_network:
    driver: bridge 