services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - 8088:8000
    depends_on:
      - db
      - redis
    env_file:
      - .env
    networks:
      - bullbot_network
    deploy:
      resources:
        limits:
          memory: 250M
        reservations:
          memory: 128M

  db:
    image: postgres:17.1-alpine
    env_file:
      - .env
    environment:
      POSTGRES_DB: bullbot_signals
      POSTGRES_USER: bullbot_user
      POSTGRES_PASSWORD: bullbot_password_2025
    ports:
      - "5438:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - bullbot_network
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    command: >
      postgres
      -c max_connections=20
      -c shared_buffers=16MB
      -c effective_cache_size=64MB
      -c maintenance_work_mem=8MB
  
  celery_worker:
    build:
      context: .
    command: celery -A src.tasks.celery_app worker --loglevel=info --concurrency=1 --max-memory-per-child=200000 --queues=signals,celery
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    env_file:
      - .env
    networks:
      - bullbot_network
    deploy:
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 100M
      
  celery_beat:
    build:
      context: .
    command: celery -A src.tasks.celery_app beat --loglevel=warning
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    env_file:
      - .env
    networks:
      - bullbot_network
    deploy:
      resources:
        limits:
          memory: 120M
        reservations:
          memory: 60M

  redis:
    image: redis:8.0-alpine
    ports:
      - "6379:6379"
    networks:
      - bullbot_network
    deploy:
      resources:
        limits:
          memory: 64M
        reservations:
          memory: 32M
    command: >
      redis-server
      --maxmemory 48mb
      --maxmemory-policy allkeys-lru
      --save "" 

volumes:
  pgdata:

networks:
  bullbot_network:
    external: true
    name: bullbot-shared-network 