services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - 8088:8000
    depends_on:
      - db
      - redis
    env_file:
      - .env
    networks:
      - bullbot_network

  db:
    image: postgres:17.1
    env_file:
      - .env
    ports:
      - "5438:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - bullbot_network
  
  celery_worker:
    build:
      context: .
    command: celery -A src.tasks.celery_app worker --loglevel=info --concurrency=2
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    env_file:
      - .env
    networks:
      - bullbot_network
      
  celery_beat:
    build:
      context: .
    command: celery -A src.tasks.celery_app beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    env_file:
      - .env
    networks:
      - bullbot_network

  redis:
    image: redis:8.0
    ports:
      - "6379:6379"
    networks:
      - bullbot_network 

volumes:
  pgdata:

networks:
  bullbot_network:
    driver: bridge 